# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sabscriber',
            options={'verbose_name': 'Sabscriber', 'verbose_name_plural': 'All Subscribers'},
        ),
    ]
