# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_delivery', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery',
                'verbose_name': 'Delivery',
            },
        ),
        migrations.CreateModel(
            name='StatusDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_delivery_name', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Status Delivery',
                'verbose_name': 'Status Delivery',
            },
        ),
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Product Order', 'verbose_name_plural': 'Product Orders'},
        ),
        migrations.AddField(
            model_name='productinorder',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price_all',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.StatusDelivery'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
