# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180103_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='status',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Status'),
        ),
    ]
