# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180104_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusdelivery',
            old_name='delivery',
            new_name='delivery_type',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='delivery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Delivery'),
        ),
    ]
