# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180104_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='delivery',
        ),
    ]
