# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_productinorder_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='delivery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Delivery'),
        ),
    ]
