# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_productinorder_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='delivery_status',
        ),
    ]
