# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_productinorder_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='discount_price',
        ),
    ]
