# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_is_main'),
        ('orders', '0016_remove_productinorder_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('product_status', models.BooleanField(default=True)),
                ('price_for_one', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number', models.IntegerField(blank=True, default=1, null=True)),
                ('price_all', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'Products In Basket',
                'verbose_name': 'Product In Basket',
            },
        ),
    ]
