# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180208_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='order',
        ),
    ]
