# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_productinbasket_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='product',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
