# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_productinbasket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
