# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20180224_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryinorder',
            options={'verbose_name': 'Delivery Product', 'verbose_name_plural': 'Delivery Products'},
        ),
        migrations.RemoveField(
            model_name='statusdelivery',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='statusdelivery',
            name='order',
        ),
        migrations.AddField(
            model_name='deliveryinorder',
            name='delivery_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.StatusDelivery'),
        ),
    ]
