# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20180225_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price_for_delivery_type',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
