# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_url',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
