# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
